# Generated by Django 2.0.3 on 2018-03-10 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=200, verbose_name='rua')),
                ('country', models.CharField(max_length=200, verbose_name='pais')),
                ('administrative_area_level_1', models.CharField(max_length=200, verbose_name='estado')),
                ('administrative_area_level_2', models.CharField(max_length=200, verbose_name='cidade')),
                ('street_number', models.CharField(max_length=30, verbose_name='número')),
                ('postal_code', models.CharField(max_length=20, verbose_name='CEP')),
                ('sublocality_level_1', models.CharField(max_length=200, verbose_name='bairro')),
                ('complement', models.CharField(blank=True, max_length=20, verbose_name='complemento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_user', to=settings.AUTH_USER_MODEL, verbose_name='endereço do usuário')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_medium', django_resized.forms.ResizedImageField(crop=['top', 'left'], force_format=None, keep_meta=True, quality=0, size=[600, 600], upload_to='profile_photo/medium')),
                ('photo_thumb', django_resized.forms.ResizedImageField(crop=['top', 'left'], force_format=None, keep_meta=True, quality=0, size=[200, 200], upload_to='profile_photo/thumb')),
                ('slug', models.SlugField(unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfils',
            },
        ),
    ]
