# Generated by Django 2.0.3 on 2018-03-10 22:53

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_medium',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['top', 'left'], force_format=None, keep_meta=True, quality=75, size=[600, 600], upload_to='profile_photo/medium'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo_thumb',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['top', 'left'], force_format=None, keep_meta=True, quality=75, size=[200, 200], upload_to='profile_photo/thumb'),
        ),
    ]
